//
// ChangePasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChangePasswordRequest: Codable {

    public var username: String
    public var newPassword: String
    public var newPasswordConfirmation: String
    public var oldPassword: String?
    public var resetToken: String?

    public init(username: String, newPassword: String, newPasswordConfirmation: String, oldPassword: String?, resetToken: String?) {
        self.username = username
        self.newPassword = newPassword
        self.newPasswordConfirmation = newPasswordConfirmation
        self.oldPassword = oldPassword
        self.resetToken = resetToken
    }

    public enum CodingKeys: String, CodingKey { 
        case username
        case newPassword = "new_password"
        case newPasswordConfirmation = "new_password_confirmation"
        case oldPassword = "old_password"
        case resetToken = "reset_token"
    }

}

