//
// ConfirmRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConfirmRequest: Codable {

    public var verificationToken: String
    public var email: String

    public init(verificationToken: String, email: String) {
        self.verificationToken = verificationToken
        self.email = email
    }

    public enum CodingKeys: String, CodingKey { 
        case verificationToken = "verification_token"
        case email
    }

}

