//
// InlineResponse409Error.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse409Error: Codable {

    public var email: Bool?
    public var username: Bool?

    public init(email: Bool?, username: Bool?) {
        self.email = email
        self.username = username
    }


}

