//
// DatabaseTicketWithoutHistoryImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DatabaseTicketWithoutHistoryImage: Codable {

    public var data: Data?
    public var contentType: String?

    public init(data: Data?, contentType: String?) {
        self.data = data
        self.contentType = contentType
    }


}

