//
// DatabaseTicketWithoutHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DatabaseTicketWithoutHistory: Codable {

    public enum Violation: String, Codable { 
        case expiredTag = "Expired Tag"
        case noTag = "No Tag"
        case improperParking = "Improper Parking"
    }
    public enum Location: String, Codable { 
        case a = "Garage A"
        case b = "Garage B"
        case c = "Garage C"
    }
    public enum Status: String, Codable { 
        case rejected = "Rejected"
        case submitted = "Submitted"
        case completed = "Completed"
    }
    /** id of ticket */
    public var _id: String
    /** Name of the ticketor */
    public var ticketorName: String?
    /** Name of the license plate */
    public var licensePlate: String?
    /** One of the enumerated violations */
    public var violation: Violation?
    /** User input to describe situation */
    public var _description: String?
    /** One of the enumerated parking to be passed */
    public var location: Location?
    /** Optional field for any additional comments */
    public var additionalComments: String?
    public var image: DatabaseTicketWithoutHistoryImage?
    public var status: Status
    public var createdAt: String
    public var updatedAt: String

    public init(_id: String, ticketorName: String?, licensePlate: String?, violation: Violation?, _description: String?, location: Location?, additionalComments: String?, image: DatabaseTicketWithoutHistoryImage?, status: Status, createdAt: String, updatedAt: String) {
        self._id = _id
        self.ticketorName = ticketorName
        self.licensePlate = licensePlate
        self.violation = violation
        self._description = _description
        self.location = location
        self.additionalComments = additionalComments
        self.image = image
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id
        case ticketorName = "ticketor_name"
        case licensePlate = "license_plate"
        case violation
        case _description = "description"
        case location
        case additionalComments = "additional_comments"
        case image
        case status
        case createdAt
        case updatedAt
    }

}

