//
// InlineResponse2004TicketsByViolation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004TicketsByViolation: Codable {

    public var expiredTag: Int?
    public var noTag: Int?
    public var improperTag: Int?

    public init(expiredTag: Int?, noTag: Int?, improperTag: Int?) {
        self.expiredTag = expiredTag
        self.noTag = noTag
        self.improperTag = improperTag
    }

    public enum CodingKeys: String, CodingKey { 
        case expiredTag = "expired_tag"
        case noTag = "no_tag"
        case improperTag = "improper_tag"
    }

}

