//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003: Codable {

    public var docs: [DatabaseTicket]?

    public init(docs: [DatabaseTicket]?) {
        self.docs = docs
    }


}

