//
// InlineResponse2004TicketsByLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004TicketsByLocation: Codable {

    public var garageA: Int?
    public var garageB: Int?

    public init(garageA: Int?, garageB: Int?) {
        self.garageA = garageA
        self.garageB = garageB
    }

    public enum CodingKeys: String, CodingKey { 
        case garageA = "garage_a"
        case garageB = "garage_b"
    }

}

