//
// InlineResponse4001Error.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse4001Error: Codable {

    public var username: Bool?
    public var oldPassword: Bool?
    public var newPassword: Bool?
    public var resetToken: Bool?

    public init(username: Bool?, oldPassword: Bool?, newPassword: Bool?, resetToken: Bool?) {
        self.username = username
        self.oldPassword = oldPassword
        self.newPassword = newPassword
        self.resetToken = resetToken
    }

    public enum CodingKeys: String, CodingKey { 
        case username
        case oldPassword = "old_password"
        case newPassword = "new_password"
        case resetToken = "reset_token"
    }

}

