//
// InlineResponse4001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse4001: Codable {

    public var error: InlineResponse4001Error?

    public init(error: InlineResponse4001Error?) {
        self.error = error
    }


}

