//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var userId: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var username: String?

    public init(userId: String?, firstName: String?, lastName: String?, email: String?, username: String?) {
        self.userId = userId
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "_userId"
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case username
    }

}

