//
// InlineResponse2004.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004: Codable {

    public var totalTickets: Int
    public var ticketsByViolation: InlineResponse2004TicketsByViolation
    public var ticketsByLocation: InlineResponse2004TicketsByLocation

    public init(totalTickets: Int, ticketsByViolation: InlineResponse2004TicketsByViolation, ticketsByLocation: InlineResponse2004TicketsByLocation) {
        self.totalTickets = totalTickets
        self.ticketsByViolation = ticketsByViolation
        self.ticketsByLocation = ticketsByLocation
    }

    public enum CodingKeys: String, CodingKey { 
        case totalTickets = "total_tickets"
        case ticketsByViolation = "tickets_by_violation"
        case ticketsByLocation = "tickets_by_location"
    }

}

