//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002: Codable {

    public var ticketId: String?

    public init(ticketId: String?) {
        self.ticketId = ticketId
    }

    public enum CodingKeys: String, CodingKey { 
        case ticketId = "ticket_id"
    }

}

