//
// SignUpRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SignUpRequest: Codable {

    public var firstName: String
    public var lastName: String
    public var email: String
    public var username: String
    public var password: String
    public var passwordConfirmation: String

    public init(firstName: String, lastName: String, email: String, username: String, password: String, passwordConfirmation: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.username = username
        self.password = password
        self.passwordConfirmation = passwordConfirmation
    }

    public enum CodingKeys: String, CodingKey { 
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case username
        case password
        case passwordConfirmation = "password_confirmation"
    }

}

