//
// TicketBase.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketBase: Codable {

    public enum Violation: String, Codable { 
        case expiredTag = "Expired Tag"
        case noTag = "No Tag"
        case improperParking = "Improper Parking"
    }
    public enum Location: String, Codable {
        case a = "Garage A"
        case b = "Garage B"
        case c = "Garage C"
    }
    /** Binary representation of image to upload */
    public var image: Data?
    /** Name of the license plate */
    public var licensePlate: String?
    /** One of the enumerated violations */
    public var violation: Violation?
    /** User input to describe situation */
    public var _description: String?
    /** One of the enumerated parking to be passed */
    public var location: Location?
    /** Optional field for any additional comments */
    public var additionalComments: String?

    public init(image: Data?, licensePlate: String?, violation: Violation?, _description: String?, location: Location?, additionalComments: String?) {
        self.image = image
        self.licensePlate = licensePlate
        self.violation = violation
        self._description = _description
        self.location = location
        self.additionalComments = additionalComments
    }

    public enum CodingKeys: String, CodingKey { 
        case image
        case licensePlate = "license_plate"
        case violation
        case _description = "description"
        case location
        case additionalComments = "additional_comments"
    }

}

