//
// InlineResponse409.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse409: Codable {

    public var error: InlineResponse409Error?

    public init(error: InlineResponse409Error?) {
        self.error = error
    }


}

