//
// InlineResponse400.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse400: Codable {

    public var error: InlineResponse400Error?

    public init(error: InlineResponse400Error?) {
        self.error = error
    }


}

