//
// InlineResponse400Error.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse400Error: Codable {

    public var username: Bool?
    public var email: Bool?
    public var password: Bool?
    public var passwordConfirmation: Bool?

    public init(username: Bool?, email: Bool?, password: Bool?, passwordConfirmation: Bool?) {
        self.username = username
        self.email = email
        self.password = password
        self.passwordConfirmation = passwordConfirmation
    }

    public enum CodingKeys: String, CodingKey { 
        case username
        case email
        case password
        case passwordConfirmation = "password_confirmation"
    }

}

